routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Index del sitio
Route::get('/', function () {
    return view('welcome');
});
//Login y registro
Auth::routes();
//Home de Autenticación
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homeReportes', 'HomeController@index_reportes')->name('home.reportes');
Route::get('/homeUsuarios', 'HomeController@index_usuarios')->name('home.usuarios');
//Reportes
Route::post('/reportes/actualizar/{id}',['as' => 'reportes.actualizar', 'uses' => 'ReporteController@actualizar']);
Route::get('/reportes/obtener/{id}',['as' => 'reportes.obtener_por_id', 'uses' => 'ReporteController@obtenerPorId']);
Route::delete('/reportes/borrar',['as' => 'reportes.borrar', 'uses' => 'ReporteController@borrar']);
Route::resource('reportes', 'ReporteController');
//Usuarios
Route::post('/usuarios/actualizar/{id}',['as' => 'usuarios.actualizar', 'uses' => 'UsuarioController@actualizar']);
Route::get('/usuarios/obtener/{id}',['as' => 'usuarios.obtener_por_id', 'uses' => 'UsuarioController@obtenerPorId']);
Route::get('/usuarios/obtenerTodos',['as' => 'usuarios.index', 'uses' => 'UsuarioController@index']);
Route::delete('/usuarios/borrar',['as' => 'usuarios.borrar', 'uses' => 'UsuarioController@borrar']);
Route::resource('usuarios', 'UsuarioController');

//Contar los errores de un formulario, para prevenir enviar un formulario con datos erroneos
Route::post('/contar_errores_form/{mensaje}',['as' => 'contar_errores_form', 'uses' => 'HomeController@contar_errores_form']);
//Validar los campos de los formularios
Route::post('/validar_formulario',['as' => 'validar_formulario', 'uses' => 'HomeController@validar_formulario']);

app/Http/Controllers/ReporteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;
use App\Models\Report;
use Session;

class ReporteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));

        if ($rol && Session::get('role_us') == 'admin') {
            $reportes = Report::with('user');
            return response()->json([
                'validate' => true,
                'data' => $reportes,
                'status' => 200
            ], 200);   
        } elseif ($rol && Session::get('role_us') == 'employee') {
            $reportes = Report::where('user_id', Session::get('id_us'))->with('user')->get();
            return response()->json([
                'validate' => true,
                'data' => $reportes,
                'status' => 200
            ], 200);  
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'employee') {
            $reporte = null;
            return view('reportes.add-edit', compact('reporte'));
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes crear reportes, solo puedes consultarlos');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rol = $request->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $reporte = new Report();
            $reporte->name = $request->name;
            $reporte->description = $request->description;
            $reporte->user_id = $request->user_id;
            $usuario = User::where('id', Session::get('id_us'))->first();
            $reporte->user()->associate($usuario)->save();
            return response()->json([
                'validate' => true,
                'msj'=>'Reporte creado correctamente',
                'status' => 200
            ], 200);  
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $reporte = Report::find($id);
            return view('reportes.add-edit', compact('reporte'));
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function actualizar($id, Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $reporte = Report::find($id);
            if ($req->name != null) {
                $reporte->name = $req->name;
            }
            if ($req->description != null) {
                $reporte->description = $req->description;
            }
            $reporte->save();
        
            return response()->json([
                'validate' => true,
                'msj'=>'Reporte actualizado correctamente',
                'status' => 200
            ], 200);  
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function borrar(Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $report = Report::find($req->id);
            $report->user()->dissociate();
            $report->delete();

            Session::flash('type_message', 'exito');
            Session::flash('message', 'El reporte ha sido borrado con éxito');
            return response()->json([
                'validate' => true,
                'msj'=>'Reporte eliminado correctamente',
                'status' => 200
            ], 200);    
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }

    /**
     * Get the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function obtenerPorId(Request $req, $id)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $report = Report::find($id);
            return response()->json([
                'validate' => true,
                'data'=> $report,
                'status' => 200
            ], 200);    
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeReportes');
        }
    }
}

resources/views/reportes/add-edit.blade.php
@extends('layouts.users')
@section('breadcrumbs')
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Reportes</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{route('home')}}">Reportes</a>
                        </li>
                        <?php if ($reporte == null) { ?>
                            <li class="active">Crear reporte
                            </li>
                        <?php } else { ?>
                            <li class="active">Editar reporte
                            </li>
                        <?php } ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body w-50 m-auto">
                        <form  
                            <?php if ($reporte != null) {?>
                                action="{{route('reportes.update', $reporte->id)}}"
                                method="PUT"
                            <?php } elseif ($reporte == null) { ?>
                                action="{{route('reportes.store')}}"
                                method="POST"
                            <?php } ?> id="formulario">
                            <div class="form-group">
                            <input type="text" class="form-control" onChange='actualiza("nombre");' <?php if ($reporte == null) { ?> data-onload='nombre' <?php } ?> name="nombre" id="nombre" value="<?php if ($reporte != null ) { echo $reporte->name; } else { echo ''; }?>" placeholder="Nombre">
                                <div class="w-100 text-center"><span id="nombre_v"></span></div>
                            </div>
                            <div class="form-group">
                            <input type="text" class="form-control" onChange='actualiza("descripcion");' <?php if ($reporte == null) { ?> data-onload='descripcion' <?php } ?> name="descripcion" id="descripcion" value="<?php if ($reporte != null ) { echo $reporte->description; } else { echo ''; }?>" placeholder="Descripción">
                                <div class="w-100 text-center"><span id="descripcion_v"></span></div>
                            </div>
                            <div class="form-group">
                                <button id="enviar" class="form-control btn btn-primary" <?php if ($reporte != null) { ?>onclick="confirmar('PUT', {{$reporte->id}})" <?php } else { ?> onclick="confirmar('POST', 0)" <?php } ?> type="button">
                                    <i class="fa fa-check"></i>  Enviar
                                </button>
                                <!-- <button id="enviar" class="form-control btn btn-primary" type="submit">
                                    <i class="fa fa-check"></i>  Enviar
                                </button> -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        var midata;
        function confirmar(type_method, id)
        {
            if (confirm('¿Deseas enviar el formulario?')) {
                // var form = $('#formulario')[0];
                // midata = new FormData(form);
                var midata = new FormData();
                midata.append('name', $('#nombre').val());
                midata.append('description', $('#descripcion').val());
                midata.append('user_id', '<?= Session::get('id_us') ?>');
                let url_report = "";
                if (type_method == 'POST') {
                    url_report = "{{route('reportes.store')}}";
                } else if (type_method == 'PUT') {
                    type_method = "POST";
                    url_report = "{{route('reportes.actualizar',($reporte != null)?$reporte->id:'')}}";
                }
                $.ajax({
                    url:    url_report,
                    type:   type_method,
                    contentType: false,
                    data: midata,  // mandamos el objeto formdata que se igualo a la variable data
                    processData: false,
                    cache: false,
                    async: true,
                    success: function(data){
                        console.log(data);
                        if(data.status == 200){
                            alert(data.msj);
                            cargarTabla();
                        }
                    }
                });
            }
        }
    </script>
@endsection

resources/views/reportes/index.blade.php
@extends('layouts.users')
@section('breadcrumbs')
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Reportes</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li class="active">Listado de reportes
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <!-- Modal -->
    <div class="modal fade" id="modalReporte" tabindex="-1" role="dialog" aria-labelledby="modalReporteCentradoTitulo" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalReporteTitulo"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                <form id="formularioNuevo">
                    <div class="form-group">
                        <input required type="text" class="form-control" onChange='actualiza("nombre");' name="nombre" id="nombre" placeholder="Nombre">
                        <div class="w-100 text-center"><span id="nombre_v"></span></div>
                    </div>
                    <div class="form-group">
                        <input required type="text" class="form-control" onChange='actualiza("descripcion");' name="descripcion" id="descripcion" placeholder="Descripción">
                        <div class="w-100 text-center"><span id="descripcion_v"></span></div>
                    </div>
                </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary rounded" id="guardarReporte" >Guardar</button>
                    <button type="button" class="btn btn-secondary rounded" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="panel-body">
                        @if (Session::has('id_us') && Session::get('role_us') == 'employee')
                            <button type="button" class="btn btn-primary rounded" id="nuevoReporte">
                                <i class="fa fa-plus-circle"></i> Nuevo reporte
                            </button>
                            <!-- <div class="pull-left">
                                <a href="{{route('reportes.create')}}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Nuevo reporte</a>
                            </div> -->
                        @endif
                        <br>
                        <hr>
                        <div style="overflow-y:scroll">
                            <table id="lookup" class="table w-100" id="tabla_reportes">  
                            <thead bgcolor="#eeeeee" align="center">
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                    <th class="text-center"> Opciones </th> 
                                </tr>
                                </thead>
                                <tbody id="lookup-tbody">
                                    @foreach ($reportes as $report)
                                        <tr>
                                            <td class="text-center">{{$report->id}}</td>
                                            <td class="text-center">{{$report->name}}</td>
                                            <td class="text-center">{{$report->description}}</td>
                                            <td class="d-flex justify-content-center">
                                                <!-- <a href="{{route('reportes.edit',$report->id)}}" class="pr-2">
                                                    <button class="btn btn-warning" >
                                                        <i class="fa fa-pencil"></i>&nbsp;Editar
                                                    </button>
                                                </a> -->
                                                <button type="button" onclick="editarReporte('<?=$report->id?>')" class="btn btn-warning rounded" name="Editar">
                                                    <i class="fa fa-pencil"></i> Editar
                                                </button>&nbsp;
                                                <button type="button" onclick="confirmarBorrar('¿Estás seguro que deseas eliminar el reporte?','<?= $report->id ?>')" class="btn btn-danger rounded" name="Eliminar">
                                                    <i class="fa fa-trash"></i> Eliminar
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach
                                    @if (count($reportes) == 0)
                                        <tr>
                                            <td colspan="4" class="text-center">
                                                No hay reportes para mostrar
                                            </td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                        <div class="m-auto d-flex justify-content-center">
                            {{$reportes->appends($_GET)->links()}}
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        var midata, id_report;
        function confirmarAgregarEditar(type_method, id)
        {
            var message = '';
            if (type_method == 'POST') {
                message = '¿Deseas guardar el reporte?'; 
            } else {
                message = '¿Deseas actualizar el reporte?'; 
            }
            if (confirm(message)) {
                // var form = $('#formulario')[0];
                // midata = new FormData(form);
                var midata = new FormData();
                midata.append('name', $('#nombre').val());
                midata.append('description', $('#descripcion').val());
                midata.append('user_id', '<?= Session::get('id_us') ?>');
                if (type_method == 'POST') {
                    url_report = "{{route('reportes.store')}}";
                } else if (type_method == 'PUT') {
                    type_method = "POST";
                    url_report = '/reportes/actualizar/'+id;
                }
                $.ajax({
                    url:    url_report,
                    type:   type_method,
                    contentType: false,
                    data: midata,  
                    processData: false,
                    cache: false,
                    async: true,
                    success: function(data){
                        console.log(data);
                        if(data.status == 200){
                            alert(data.msj);
                            $('#modalReporte').modal('hide');
                            cargarTabla();
                        }
                    }
                });
            }
        }
        function confirmarBorrar(mensaje, id)
        {
            if (confirm(mensaje)) {
                let url_delete = "{{route('reportes.borrar')}}";
                $.ajax({
                    url:    url_delete,
                    type:   "DELETE",
                    async: true,
                    data: {"_token": "{{ csrf_token() }}", 'id': id},
                    success: function(data){
                        if(data.status == 200){
                            alert(data.msj);
                            cargarTabla();
                        }
                    }
                });
            }
        }
        function editarReporte(id)
        {
            $.ajax({
                url     : '/reportes/obtener/'+id,
                method  : 'GET',
                success : function(response){
                    let datos = response.data;
                    $('#nombre').val(datos.name);
                    $('#descripcion').val(datos.description);
                    $('#nombre_v').html('');
                    $('#descripcion_v').html('');
                    $('#nombre_v').removeClass('fa fa-check fa-remove');
                    $('#descripcion_v').removeClass('fa fa-check fa-remove');
                    $('#modalReporte').modal('show');
                    $('#modalReporteTitulo').html('Editar reporte');
                    $('#guardarReporte').attr('onclick', 'confirmarAgregarEditar("PUT", '+id+')');
                }
            });
        }
        function cargarTabla()
        {
            $.ajax({
                url     : "{{ route('reportes.index')}}",
                method  : 'GET',
                success : function(response){
                    let lista = response.data;
                    var htmlCode = '';
                    $.each(lista, function(index, item){
                        htmlCode += 
                            `<tr>
                                <td class="text-center">`+item.id+`</td>
                                <td class="text-center">`+item.name+`</td>
                                <td class="text-center">`+item.description+`</td>
                                <td class="d-flex justify-content-center">
                                    <button type="button" onclick="editarReporte(`+item.id+`)" class="btn btn-warning rounded" name="Editar">
                                        <i class="fa fa-pencil"></i> Editar
                                    </button>&nbsp;
                                    <button type="button" onclick="confirmarBorrar('¿Estás seguro que deseas eliminar el reporte?',`+item.id+`)" class="btn btn-danger rounded" name="Eliminar">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </button>
                                </td>
                            </tr>`;
                    });
                    if (lista == '') {
                        htmlCode += `<tr>
                                        <td colspan="4" class="text-center">
                                            No hay reportes para mostrar
                                        </td>
                                    </tr>`;
                    }
                    $('#lookup-tbody').html(htmlCode);
                }
            });
        }
        $(document).ready(function()
        {
            $('#nuevoReporte').on('click', function()
            {
                $('#nombre').val('');
                $('#descripcion').val('');
                $('#nombre_v').html('');
                $('#descripcion_v').html('');
                $('#nombre_v').removeClass('fa fa-check fa-remove');
                $('#descripcion_v').removeClass('fa fa-check fa-remove');
                $('#modalReporte').modal('show');
                $('#modalReporteTitulo').html('Nuevo reporte');
                $('#guardarReporte').attr('onclick', 'confirmarAgregarEditar("POST", 0)');
            });
        });
    </script>
@endsection