routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Index del sitio
Route::get('/', function () {
    return view('welcome');
});
//Login y registro
Auth::routes();
//Home de Autenticación
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homeReportes', 'HomeController@index_reportes')->name('home.reportes');
Route::get('/homeUsuarios', 'HomeController@index_usuarios')->name('home.usuarios');
//Reportes
Route::post('/reportes/actualizar/{id}',['as' => 'reportes.actualizar', 'uses' => 'ReporteController@actualizar']);
Route::get('/reportes/obtener/{id}',['as' => 'reportes.obtener_por_id', 'uses' => 'ReporteController@obtenerPorId']);
Route::delete('/reportes/borrar',['as' => 'reportes.borrar', 'uses' => 'ReporteController@borrar']);
Route::resource('reportes', 'ReporteController');
//Usuarios
Route::post('/usuarios/actualizar/{id}',['as' => 'usuarios.actualizar', 'uses' => 'UsuarioController@actualizar']);
Route::get('/usuarios/obtener/{id}',['as' => 'usuarios.obtener_por_id', 'uses' => 'UsuarioController@obtenerPorId']);
Route::get('/usuarios/obtenerTodos',['as' => 'usuarios.index', 'uses' => 'UsuarioController@index']);
Route::delete('/usuarios/borrar',['as' => 'usuarios.borrar', 'uses' => 'UsuarioController@borrar']);
Route::resource('usuarios', 'UsuarioController');

//Contar los errores de un formulario, para prevenir enviar un formulario con datos erroneos
Route::post('/contar_errores_form/{mensaje}',['as' => 'contar_errores_form', 'uses' => 'HomeController@contar_errores_form']);
//Validar los campos de los formularios
Route::post('/validar_formulario',['as' => 'validar_formulario', 'uses' => 'HomeController@validar_formulario']);

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;
use App\Models\Report;
use Session;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $users = User::with('roles')->get();
            return response()->json([
                'validate' => true,
                'data' => $users,
                'status' => 200
            ], 200);   
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $rol = $request->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $usuario = null;
            return view('usuarios.add-edit', compact('usuario'));
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rol = $request->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $user = new User();
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->contrasena);
            $user->status = true;
            $user->save();
            $name_role = ($request->role_user == 1)?'admin':'employee';
            $role = Role::where('name', $name_role)->first();
            $user->roles()->attach($role);
            return response()->json([
                'validate' => true,
                'msj'=>'Usuario creado correctamente',
                'status' => 200
            ], 200);  
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $rol = $request->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $usuario = User::find($id);
            return view('usuarios.add-edit', compact('usuario'));
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {
        
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function actualizar($id, Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $user = User::find($id);
            if ($req->name != null) {
                $user->name = $req->name;
            }
            if ($req->email != null) {
                $user->email = $req->email;
            }
            if ($req->password != null) {
                $user->password = bcrypt($req->password);
            }
            $user->status = true;
            $name_role = ($req->role_user == 1)?'admin':'employee';
            $role = Role::where('name', $name_role)->first();
            $user->roles()->detach();
            $user->roles()->attach($role);
            $user->save();
            return response()->json([
                'validate' => true,
                'msj'=>'Usuario actualizado correctamente',
                'status' => 200
            ], 200);  
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function borrar(Request $req)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol && Session::get('role_us') == 'admin') {
            $user = User::find($req->id);
            $user->roles()->detach();
            $user->delete();

            Session::flash('type_message', 'exito');
            Session::flash('message', 'El usuario ha sido borrado con éxito');
            return response()->json([
                'validate' => true,
                'msj'=>'Usuario eliminado correctamente',
                'status' => 200
            ], 200);    
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

    /**
     * Get the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function obtenerPorId(Request $req, $id)
    {
        $rol = $req->user()->authorizeRoles(Session::get('role_us'));
        if ($rol) {
            $user = User::with('roles')->find($id);
            return response()->json([
                'validate' => true,
                'data'=> $user,
                'status' => 200
            ], 200);    
        } else {
            Session::flash('type_message', 'error');
            Session::flash('message', 'No puedes acceder a esa sección del sitio');
            return Redirect('/homeUsuarios');
        }
    }

}

resources/views/usuarios/add-edit.blade.php
@extends('layouts.users')
@section('breadcrumbs')
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Usuarios</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{route('home.usuarios')}}">Usuarios</a>
                        </li>
                        <?php if ($usuario == null) { ?>
                            <li class="active">Crear usuario
                            </li>
                        <?php } else { ?>
                            <li class="active">Editar usuario
                            </li>
                        <?php } ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body w-50 m-auto">
                        <form  
                            <?php if ($usuario != null) {?>
                                action="{{route('usuarios.update', $usuario->id)}}"
                                method="PUT"
                            <?php } elseif ($usuario == null) { ?>
                                action="{{route('usuarios.store')}}"
                                method="POST"
                            <?php } ?> id="formulario">
                            <div class="form-group">
                            <input type="text" class="form-control" onChange='actualiza("nombre");' <?php if ($usuario == null) { ?> data-onload='nombre' <?php } ?> name="nombre" id="nombre" value="<?php if ($usuario != null ) { echo $usuario->name; } else { echo ''; }?>" placeholder="Nombre">
                                <div class="w-100 text-center"><span id="nombre_v"></span></div>
                            </div>
                            <div class="form-group">
                            <input type="email" class="form-control" onChange='actualiza("email");' <?php if ($usuario == null) { ?> data-onload='email' <?php } ?> name="email" id="email" value="<?php if ($usuario != null ) { echo $usuario->email; } else { echo ''; }?>" placeholder="Correo electrónico">
                                <div class="w-100 text-center"><span id="email_v"></span></div>
                            </div>
                            <div class="form-group">
                                <select name="tipo_usuario" class="form-control" onChange='actualiza("tipo_usuario");' <?php if ($usuario == null) { ?> data-onload='tipo_usuario' <?php } ?> id="tipo_usuario">
                                    <option value="-1">Seleccione una opción</option>
                                    <option value="1" <?php if ($usuario != null && $usuario->roles[0]->name == 'admin') { echo 'selected'; } ?>>Administrador</option>
                                    <option value="2" <?php if ($usuario != null && $usuario->roles[0]->name == 'employee') { echo 'selected'; } ?>>Empleado</option>
                                </select>
                                <div class="w-100 text-center"><span id="tipo_usuario_v"></span></div>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" onChange='actualiza("contrasena");' data-onload='contrasena' name="contrasena" id="contrasena" placeholder="Contraseña">
                                <div class="w-100 text-center"><span id="contrasena_v"></span></div>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" onChange='actualiza("password_confirmation");' name="password_confirmation" id="password_confirmation" placeholder="Confirmar Contraseña">
                                <div class="w-100 text-center"><span id="password_confirmation_v"></span></div>
                            </div>
                            <div class="form-group">
                                <button id="enviar" class="form-control btn btn-primary" <?php if ($usuario != null) { ?>onclick="confirmar('PUT', {{$usuario->id}})" <?php } else { ?> onclick="confirmar('POST', 0)" <?php } ?> type="button">
                                    <i class="fa fa-check"></i>  Enviar
                                </button>
                                <!-- <button id="enviar" class="form-control btn btn-primary" type="submit">
                                    <i class="fa fa-check"></i>  Enviar
                                </button> -->
                            </div>
                            
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        var midata;
        function confirmar(type_method, id)
        {
            if (confirm('¿Deseas enviar el formulario?')) {
                // var form = $('#formulario')[0];
                // midata = new FormData(form);
                var midata = new FormData();
                midata.append('name', $('#nombre').val());
                midata.append('email', $('#email').val());
                midata.append('password', $('#contrasena').val());
                midata.append('role_user', $('#tipo_usuario').val());
                let url_user = "";
                if (type_method == 'POST') {
                    url_user = "{{route('usuarios.store')}}";
                } else if (type_method == 'PUT') {
                    type_method = "POST";
                    url_user = "{{route('usuarios.actualizar',($usuario != null)?$usuario->id:'')}}";
                }
                $.ajax({
                    url:    url_user,
                    type:   type_method,
                    contentType: false,
                    data: midata,  // mandamos el objeto formdata que se igualo a la variable data
                    processData: false,
                    cache: false,
                    async: true,
                    success: function(data){
                        console.log(data);
                        if(data.status == 200){
                            alert(data.msj);
                            cargarTabla();
                        }
                    }
                });
            }
        }
    </script>
@endsection